### PR TITLE
Task06-13, Group09, Козловцева Мария

### PR DESCRIPTION
**Pull request by mamaria-k**
@yeputons

### CODE REVIEW

**Comment by mamaria-k** [comment]
@yeputons, https://github.com/yeputons/spring-2019-paradigms-tasks/pull/77

**Comment by mamaria-k** [comment]
@yeputons, сделано

**Comment by mamaria-k** [comment]
@yeputons

**Comment by mamaria-k** [comment]
@yeputons

**Comment by mamaria-k** [comment]
@yeputons

**Comment by mamaria-k** [comment]
@yeputons

**Comment by mamaria-k** [comment]
@yeputons

**Review by yeputons — APPROVED** [review]
Got it, #77 .

**Pull request closed without merging**
